/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
/**
 *
 * @author jocel
 */
public class Informacion extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnLicencia = new javax.swing.JButton();
        btnPreguntas = new javax.swing.JButton();
        lblManual = new javax.swing.JLabel();
        lblManualTex = new javax.swing.JLabel();
        lblAcerca1 = new javax.swing.JLabel();
        lblAcercaTex1 = new javax.swing.JLabel();
        lblFondoInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoSalir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 4, 50, 40));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoInicio.png"))); // NOI18N
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 5, 50, 40));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoAtras.png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 70, 60));

        btnLicencia.setBackground(new java.awt.Color(153, 153, 153));
        btnLicencia.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        btnLicencia.setText("Licencia de uso");
        btnLicencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, -1, 30));

        btnPreguntas.setBackground(new java.awt.Color(153, 153, 153));
        btnPreguntas.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        btnPreguntas.setText("Preguntas frecuentes");
        btnPreguntas.setActionCommand("");
        btnPreguntas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, -1, 30));

        lblManual.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lblManual.setText("Manual básico");
        getContentPane().add(lblManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 220, 30));

        lblManualTex.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        lblManualTex.setText("<html>Esta es una aplicación sencilla, que tiene como objetivo el almacenamiento de datos y la interacción entre el usuario y los mismos, a través de un registro de usuario, imágenes y frases aleatorias, que a su vez son entretenimiento de la aplicación.</html>");
        lblManualTex.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblManualTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 410, 180));

        lblAcerca1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lblAcerca1.setText("Acerca de nosotros");
        getContentPane().add(lblAcerca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 220, 30));

        lblAcercaTex1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        lblAcercaTex1.setText("<html>Somos estudiantes de la Universidad Pascual Bravo, Tecnología en Desarrollo de Software, esta es la materia de Herramientas de Programación III.\nNuestros motivos para el desarrollo de este software son: *Aplicar los conocimientos adquiridos, al servicio de los clientes, solucionar sus necesidades.\n*Desarrollar un software de forma concreta desde el inicio (con planeación, diseño, estructura y programación).\nEste software fue llamado \"MIXTURA\", lo consideramos mezcla y nos pareció adecuado en el contexto.</html>");
        lblAcercaTex1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblAcercaTex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 390, 220));

        lblFondoInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/FondoInformacion.jpg"))); // NOI18N
        getContentPane().add(lblFondoInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.setVisible(false);
        Saludo saludo = new Saludo();
        saludo.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        this.setVisible(false);
        Ayuda ayuda = new Ayuda();
        ayuda.setVisible(true);
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);
        Interaccion interaccion = new Interaccion();
        interaccion.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciaActionPerformed
        try {

           Desktop.getDesktop().browse(new URI("https://drive.google.com/drive/folders/1HGDF4odnFlz8uw7wsKjlXiH-Oo_kLc7u?usp=sharing"));

        } catch (URISyntaxException | IOException ex) {

           System.out.println(ex);
        }                    
    }//GEN-LAST:event_btnLicenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLicencia;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAcerca1;
    private javax.swing.JLabel lblAcercaTex1;
    private javax.swing.JLabel lblFondoInformacion;
    private javax.swing.JLabel lblManual;
    private javax.swing.JLabel lblManualTex;
    // End of variables declaration//GEN-END:variables
}
