/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Datos.Datos_trabajo;
import Datos.Leer_mensaje;
import Negocios.Control;
import static Presentacion.Interaccion.nombreUsuarioOut;

/**
 *
 * @author Equipo
 */
public class Ingreso_Datos extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_Datos
     */
    public Ingreso_Datos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonRetornar = new javax.swing.JButton();
        nombreUsuarioInn = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/images/icono_IngresaDatos_imagen2.jpg"))); // NOI18N
        getContentPane().add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/images/Nombre_IngresaDatos_imagen3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        BotonRetornar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/images/Retorno.png"))); // NOI18N
        BotonRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 80, 60));

        nombreUsuarioInn.setBackground(new java.awt.Color(204, 204, 204));
        nombreUsuarioInn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombreUsuarioInn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreUsuarioInn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(nombreUsuarioInn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 470, 40));

        BtnIngresar.setBackground(new java.awt.Color(0,0,0,1));
        BtnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/images/Ingresar_IngresarDatos_imagen4.png"))); // NOI18N
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 210, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/images/fondo_IngresaDatos_imagen1.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetornarActionPerformed
        this.setVisible(false);
        Saludo saludo = new Saludo();
        saludo.setVisible(true);
    }//GEN-LAST:event_BotonRetornarActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
       this.setVisible(false);
       Interaccion interaccion = new Interaccion();
       interaccion.setVisible(true);
       Interaccion.nombreUsuarioOut.setText(nombreUsuarioInn.getText());
       
       Control control = new Control(interaccion);
       
       Datos_trabajo men = control.getFrase();
       Interaccion.lblFrase.setText("<html>"+men.getMensaje()+"</html>");
       Interaccion.lblDonar.setText("<html>"+men.getDonacion()+"</html>");
       
    }//GEN-LAST:event_BtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRetornar;
    public javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField nombreUsuarioInn;
    // End of variables declaration//GEN-END:variables
}
