/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Negocios.Control;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
 
/**
 *
 * @author jocel
 */
public class Interaccion extends javax.swing.JFrame {

    /**
     * Creates new form Interaccion
     */
    public Interaccion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        btnAcercaDe = new javax.swing.JButton();
        btnDonar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lblFrase = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        nombreUsuarioOut = new javax.swing.JTextField();
        lblDonar = new javax.swing.JLabel();
        lblFondoInteraccion = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcercaDe.setBackground(new java.awt.Color(153, 153, 153));
        btnAcercaDe.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        btnAcercaDe.setText("Acerca de... ");
        btnAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, -1, 40));

        btnDonar.setBackground(new java.awt.Color(153, 153, 153));
        btnDonar.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        btnDonar.setText("Donar");
        btnDonar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 110, 40));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoInicio.png"))); // NOI18N
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 5, 50, 40));

        lblFrase.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFrase.setText("<html></html>");
        lblFrase.setToolTipText("");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 330, 190));
        lblFrase.getAccessibleContext().setAccessibleName(""); // NOI18N

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/imagenmuestra.jpg"))); // NOI18N
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 229, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoSalir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 4, 50, 40));

        nombreUsuarioOut.setEditable(false);
        nombreUsuarioOut.setBackground(new java.awt.Color(0,0,0,1));
        nombreUsuarioOut.setFont(new java.awt.Font("Comic Sans MS", 2, 30)); // NOI18N
        nombreUsuarioOut.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombreUsuarioOut.setBorder(null);
        nombreUsuarioOut.setOpaque(false);
        getContentPane().add(nombreUsuarioOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 290, 60));

        lblDonar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblDonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 170, 50));

        lblFondoInteraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/FondoInteraccion.jpg"))); // NOI18N
        getContentPane().add(lblFondoInteraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonarActionPerformed
          try {

           Desktop.getDesktop().browse(new URI("https://hp3-pascualbravo.blogspot.com/p/sitio-en-construccion.html?m=1"));

        } catch (URISyntaxException | IOException ex) {

           System.out.println(ex);
        }                                            
    }//GEN-LAST:event_btnDonarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
         this.setVisible(false);
         Saludo saludo = new Saludo();
         saludo.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        this.setVisible(false);
        Informacion informacion = new Informacion();
        informacion.setVisible(true);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnDonar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel lblDonar;
    private javax.swing.JLabel lblFondoInteraccion;
    public static javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblImagen;
    public static javax.swing.JTextField nombreUsuarioOut;
    // End of variables declaration//GEN-END:variables
}
